# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kamyar Zeinalipour
title: PhD Candidate and Research Fellow in Artificial Intelligence at the University of Siena (SAILab)
email: kamyar.zeinalipour2@unisi.it
website: https://sailab.diism.unisi.it/people/kamyar-zeinalipour

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  kamyarzeinalipour
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: kamyarzeinalipour
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0009-0006-3014-2511
googlescholar_username: RewxhZwAAAAJ
instagram_username: k4my_r

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi! I'm Kamyar, a PhD Candidate and Research Fellow at the University of Siena's Artificial Intelligence Lab (SAILab). My academic journey and professional work center around the fascinating world of Artificial Intelligence, with a special focus on Natural Language Processing (NLP) and Natural Language Understanding (NLU).



  Throughout my career, I have delved into various aspects of AI, particularly excelling in Machine Learning and Neural Networks. My passion lies in advancing the capabilities of language models, especially for low-resource languages. By improving access to AI technologies for these languages, I aim to contribute to a more inclusive and diverse digital world.

content:

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Università di Siena
        caption: 2022 - 2025
        sub_title: Ph.D. Artificial Intelligence
        quote: >
          The University of Siena, founded in 1240 in Siena, Italy, is one of the world's oldest universities. It offers diverse undergraduate, postgraduate, and doctoral programs in fields like humanities, sciences, medicine, and engineering. Renowned for academic excellence and situated in a historic city, it attracts global students. The university is also notable for its research activities and international partnerships.
        description: | # this will include new lines to allow paragraphs
            I began my Ph.D. in AI at the SAILab (Siena Artificial Intelligence Lab) at the University of Siena. Initially, my research concentrated on Physics-Informed Neural Networks. Subsequently, I focused on crossword generation for educational purposes. I developed a crossword generator based on NLP techniques and large language models (LLMs), supporting multiple languages including English, Italian, Arabic, and Turkish. Currently, my research is dedicated to knowledge graph generation from text. Throughout my Ph.D., I have collaborated with various companies such as Baker Hughes, Expert.ai, and Leonardo S.p.A.


      - layout: left
        title: Università di Siena
        caption: 2017 - 2021
        sub_title: M.Sc. Applied Mathematics 
        quote: >
          The University of Siena, founded in 1240 in Siena, Italy, is one of the world's oldest universities. It offers diverse undergraduate, postgraduate, and doctoral programs in fields like humanities, sciences, medicine, and engineering. Renowned for academic excellence and situated in a historic city, it attracts global students. The university is also notable for its research activities and international partnerships.
        description: | # this will include new lines to allow paragraphs
          During my Master's degree in Applied Mathematics at the University of Siena, I had the opportunity to delve deeply into mathematical concepts as well as Artificial Intelligence (AI) and Machine Learning (ML) principles, which are closely aligned. I chose the Data Science track, where half of the courses focused on AI-related subjects such as Machine Learning, Big Data, and Artificial Intelligence. Additionally, the curriculum included advanced mathematics courses like Advanced Algebra, Advanced Calculus, Advanced Analysis, and Advanced Statistics, which significantly bolstered my foundational understanding of AI and ML.

          For my thesis, I concentrated on Graph Neural Networks, and titled my research "ECG Signal Classification by Topological Feature Extraction and Utilizing Graph Isomorphism Networks."

      - layout: left
        title: University Of Hormozgan
        caption: 2012 - 2017
        sub_title: B.Sc. Applied statistics
        quote: >
          University Of Hormozgan is a public higher education institution located in Bandar Abbas, Iran. Established in 1991, the university offers a range of undergraduate, graduate, and doctoral programs across various fields of study. These fields often include engineering, humanities, basic sciences, marine sciences, and social sciences, among others.

          The university aims to provide quality education and foster research and development in the region. It typically collaborates with other academic institutions, industry, and government to contribute to the socio-economic development of Hormozgan Province and beyond.
        description: | # this will include new lines to allow paragraphs
          During my bachelor's degree in Applied Statistics, I had the valuable opportunity to delve deeply into the concepts of statistics and probability, which constitute the foundational elements of many AI and ML algorithms. My thesis focused on "The Effect of Economic Indicators on the First and Second Markets of the Tehran Stock Exchange."
                  
      

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

           
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.      


      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

           


      - layout: left
        title: State manegement and planing organization 
       # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Data Analyst
        caption: Jun 2016 - Mar 2017
        quote: >
          Bandarabbas, Iran
        description: | # this will include new lines to allow paragraphs
            As a Demographic and Statistical Analyst, I performed comprehensive demographic and statistical analyses using Excel, SPSS, and R. My role involved gathering and managing datasets from various sources, ensuring their accuracy and relevance, as well as cleaning and preprocessing data for in-depth analysis. Utilizing advanced statistical methods, I conducted descriptive, inferential, and regression analyses to identify trends, patterns, and insights. Additionally, I analyzed population demographics to provide insights into current trends and forecast future changes, ultimately supporting strategic decision-making and research initiatives.


      - layout: left
        title: Gilda Research Company
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Statistican
        caption: Feb 2015 - May 2017 \n
         Bandarabbas, Iran
        #quote: >
          
        description: | # this will include new lines to allow paragraphs
           As a dedicated statistician, I leveraged SPSS, Python, and R to conduct comprehensive statistical analyses for surveys, providing accurate and actionable insights. My expertise included designing, implementing, and interpreting complex survey data with a variety of techniques such as descriptive and inferential statistics, and predictive modeling. I ensured data integrity through meticulous cleaning and validation while creating clear visualizations and reports to communicate findings effectively. Committed to methodological rigor, I continuously enhanced my skills and stayed updated with the latest advancements in statistical methodologies and software.


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.    

# Footer
footer_show_references: true
references_title: SAILab - Via Roma, 56 53100 Siena - Italia.

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
